table 'Customer Buyer Information'
	lineageTag: 9b8d7a3a-6ec6-4d47-83e8-6b925b65680c

	column 'Buyer ID'
		dataType: int64
		formatString: 0
		lineageTag: e2c2c72b-2bf2-4b6d-b26c-272ed6d0d79d
		summarizeBy: count
		sourceColumn: Buyer ID

		annotation SummarizationSetBy = Automatic

	column 'Product ID Purchased'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 86e9996b-2bbb-446a-b84b-ee8849e07876
		summarizeBy: sum
		sourceColumn: Product ID Purchased

		annotation SummarizationSetBy = Automatic

	column 'Total Purchased'
		dataType: int64
		formatString: 0
		lineageTag: 78e9cdb7-d140-4942-999c-d77c9b9ac843
		summarizeBy: sum
		sourceColumn: Total Purchased

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 616b8fea-ad9a-43fa-8e76-caed5dc28cc0
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 3e0d1a30-0c47-48fa-bb2b-8c86e054ced1
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0bc322d3-e124-4783-b722-eaf715ed23fe
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Age Group' = IF('Customer Buyer Information'[Age] < 40, "Young Adult", IF('Customer Buyer Information'[Age] < 50, "Adult", "Senior"))
		lineageTag: dc58f78c-0629-4c93-a117-ec14f656b250
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Customer Buyer Information' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Muhammad\Desktop\EXCEL DASHBOARDS\Power-BI-main\Apocolypse Food Prep - Visualizations Tutorial.xlsx"), null, true),
				    #"Customer Buyer Information_Sheet" = Source{[Item="Customer Buyer Information",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Customer Buyer Information_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Buyer ID", Int64.Type}, {"Product ID Purchased", Int64.Type}, {"Total Purchased", Int64.Type}, {"State", type text}, {"Age", Int64.Type}, {"Customer ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

